#version 300 es
// hyprcrt single-pass screen shader (lite mode) for Hyprland's decoration:screen_shader.
// Generated by tools/crt-gen from a preset; do not edit the generated copy, edit the template.
// The whole tube model in one fragment pass: two nearest virtual scanlines, each a four-tap horizontal
// spot in linear light, energy-conserving line weights, phosphor mask, an approximate halation from the
// same taps, gamma, and optionally the curved glass. No time or pointer uniforms, so Hyprland's damage
// tracking stays on. MIT (c) 2026 Dan Expo.
precision highp float;

//@DEFINES@

in vec2 v_texcoord;
uniform sampler2D tex;
uniform vec2 fullSize;
layout(location = 0) out vec4 fragColor;

//@COMMON@

// one virtual source pixel: nearest at the block centre (an even pitch lands on a texel corner, so the
// linear sampler averages the central 2x2 for free)
vec3 crt_fetch(float col, float row) {
    vec2 lim = floor(fullSize / PITCH) - 1.0;
    vec2 c   = clamp(vec2(col, row), vec2(0.0), lim);
    return crt_lin(texture(tex, (c + 0.5) * PITCH / fullSize).rgb);
}

// a source row through the horizontal spot at source column u; also hands back the plain mean of the
// four taps, the cheap stand-in for the blurred picture the halation needs
vec3 crt_spot(float u, float row, out vec3 mean) {
    vec4  wg, wr;
    float iu;
    crt_spot_weights(u, HARD_PIX, HARD_PIX_R, wg, wr, iu);
    vec3 acc = vec3(0.0);
    mean     = vec3(0.0);
    for (int k = 0; k < 4; k++) {
        vec3 c = crt_fetch(iu - 1.0 + float(k), row);
        acc.r += c.r * wr[k];
        acc.gb += c.gb * wg[k];
        mean += c;
    }
    mean *= 0.25;
    return acc;
}

void main() {
    vec2  uv  = v_texcoord;
    float vig = 1.0;
#if CURVE
    vig = crt_glass(uv, WARP_X, WARP_Y, VIGNETTE);
#endif
    vec2  px  = uv * fullSize;  // flat-space physical pixel
    vec2  src = px / PITCH;     // in virtual source pixels

    float v  = src.y - 0.5;
    float r0 = floor(v);
    float d0 = v - r0, d1 = 1.0 - d0;

    vec3 ma, mb;
    vec3 a = crt_spot(src.x, r0, ma);
    vec3 b = crt_spot(src.x, r0 + 1.0, mb);

    float wa, wb;
#if FLAT_LINES
    wa = (1.0 - d0) * (1.0 - HALO_AMT);
    wb = d0 * (1.0 - HALO_AMT);
#else
    float la = clamp(max(a.r, max(a.g, a.b)), 0.0, 1.0);
    float lb = clamp(max(b.r, max(b.g, b.b)), 0.0, 1.0);
    wa       = crt_scan_weight(d0, la, SIG_DARK, SIG_BRIGHT, BOOST_CAP) * (1.0 - HALO_AMT);
    wb       = crt_scan_weight(d1, lb, SIG_DARK, SIG_BRIGHT, BOOST_CAP) * (1.0 - HALO_AMT);
#endif
    vec3 val = a * wa + b * wb + (ma + mb) * 0.5 * HALO_AMT;
    val *= crt_mask(px, MASK, MASK_PITCH, MASK_LIGHT, MASK_DARK, SLOT_DIM);
    fragColor = vec4(crt_enc(val * GAIN, INV_GAMMA) * vig, 1.0);
}
